var ListEmployee = [
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    },
    {
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên',
        EmployeeCode: 'NV000001',
        FullName: 'Nguyễn Tiến Xuân',
        DateOfBirth: new Date(),
        Gender: 'Nam',
        Address: 'Sơn Thủy, Thanh Thủy, Phú Thọ, Việt Nam',
        Department: 'Phòng ban hành chính',
        Salary: 3000000,
        Description: 'Mô tả chi tiết nhân viên'
    }
];